### PR TITLE
Replace old sql dump with new dump from deployment

### PR DESCRIPTION
**Pull request by raphael-s**
I dumped the SQL from the database used in the deployment (arctic2). The old script had some issues probably caused by a line deleted by accident.

### CODE REVIEW

**Comment by raphael-s** [comment]
Man eifach nie gmerged @Chiirali 😢

**Review by p-svacha — APPROVED** [review]
approved

**Review by Chiirali — APPROVED** [review]

**Comment by Chiirali** [comment]
lg2m

**Comment by raphael-s** [comment]
Hold up, gotta download to merge 🤪

**Pull request merged**
